# Generated by Django 6.0.4 on 2026-04-26 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('category', models.CharField(choices=[('liten-sjokoladeboks', 'Liten sjokoladeboks'), ('stor-sjokoladeboks', 'Stor sjokoladeboks'), ('sjokoladebarer', 'Sjokoladebarer')], max_length=50)),
                ('size', models.CharField(max_length=50)),
                ('price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('price_min', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('price_max', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('image', models.ImageField(blank=True, upload_to='products/')),
                ('flavors', models.JSONField(default=list)),
                ('blurb', models.TextField()),
                ('in_stock', models.BooleanField(default=True)),
                ('batch_number', models.CharField(max_length=10)),
                ('batch_count', models.PositiveIntegerField(default=0)),
                ('batch_total', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['category', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Truffle',
            fields=[
                ('id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('color', models.CharField(max_length=7)),
                ('note', models.CharField(max_length=200)),
            ],
        ),
    ]
