# Generated by Django 6.0.5 on 2026-05-17 10:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="variant_group",
            field=models.CharField(blank=True, default="", max_length=64),
        ),
        migrations.AddField(
            model_name="product",
            name="variant_label",
            field=models.CharField(blank=True, default="", max_length=64),
        ),
    ]
