# Generated by Django 6.0.5 on 2026-05-17 10:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0002_product_variant_group_product_variant_label"),
    ]

    operations = [
        migrations.AddField(
            model_name="truffle",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
    ]
