# Generated by Django 6.0.4 on 2026-04-26 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.CharField(editable=False, max_length=20, unique=True)),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=10)),
                ('shipping', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(choices=[('Bekreftet', 'Bekreftet'), ('Pakkes', 'Pakkes'), ('Sendt', 'Sendt'), ('Levert', 'Levert')], default='Bekreftet', max_length=20)),
                ('payment_method', models.CharField(choices=[('vipps', 'Vipps'), ('card', 'Card'), ('klarna', 'Klarna'), ('invoice', 'Invoice')], max_length=20)),
                ('ship_first_name', models.CharField(max_length=100)),
                ('ship_last_name', models.CharField(max_length=100)),
                ('ship_email', models.EmailField(max_length=254)),
                ('ship_phone', models.CharField(max_length=30)),
                ('ship_address', models.CharField(max_length=300)),
                ('ship_postal_code', models.CharField(max_length=10)),
                ('ship_city', models.CharField(max_length=100)),
                ('ship_country', models.CharField(default='Norge', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('variant', models.CharField(blank=True, max_length=50)),
                ('initials', models.CharField(blank=True, max_length=10)),
                ('custom_slots', models.JSONField(blank=True, null=True)),
            ],
        ),
    ]
