# Generated by Django 6.0.4 on 2026-04-28 12:53

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='authorized_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='captured_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='last_vipps_sync_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='payment_status',
            field=models.CharField(choices=[('PENDING', 'Pending — no payment created yet'), ('CREATED', 'Payment created with Vipps, awaiting user'), ('AUTHORIZED', 'User approved, funds reserved'), ('CAPTURED', 'Funds transferred to merchant'), ('PARTIALLY_REFUNDED', 'Some amount refunded'), ('REFUNDED', 'Fully refunded'), ('CANCELLED', 'Cancelled before capture'), ('ABORTED', 'User aborted in Vipps'), ('EXPIRED', 'Payment request expired'), ('TERMINATED', 'Terminated by merchant'), ('FAILED', 'Capture failed and could not be recovered')], db_index=True, default='PENDING', max_length=24),
        ),
        migrations.AddField(
            model_name='order',
            name='vipps_authorized_amount',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='order',
            name='vipps_cancel_idempotency_key',
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='vipps_cancelled_amount',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='order',
            name='vipps_capture_idempotency_key',
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='vipps_captured_amount',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='order',
            name='vipps_currency',
            field=models.CharField(default='NOK', max_length=3),
        ),
        migrations.AddField(
            model_name='order',
            name='vipps_psp_reference',
            field=models.CharField(blank=True, help_text="Vipps' pspReference for the CREATED event (payment-level ID)", max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='vipps_redirect_url',
            field=models.URLField(blank=True, max_length=2000, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='vipps_reference',
            field=models.CharField(blank=True, db_index=True, help_text='Merchant reference sent to Vipps. Format: sl-{order_id:05d}-{8 hex}', max_length=64, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='order',
            name='vipps_refunded_amount',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['payment_status', 'created_at'], name='orders_orde_payment_e2cb15_idx'),
        ),
    ]
