# Generated by Django 6.0.4 on 2026-04-29 16:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_order_authorized_at_order_captured_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('vipps', 'Vipps')], max_length=20),
        ),
        migrations.CreateModel(
            name='OrderAuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('action', models.CharField(choices=[('order_created', 'Order created'), ('payment_status_changed', 'Payment status changed'), ('fulfillment_changed', 'Fulfillment status changed')], max_length=32)),
                ('from_value', models.JSONField(blank=True, null=True)),
                ('to_value', models.JSONField(blank=True, null=True)),
                ('source', models.CharField(choices=[('storefront', 'Storefront'), ('admin', 'Admin'), ('webhook', 'Vipps webhook'), ('reconciler', 'Vipps reconciler'), ('system', 'System / cron')], max_length=16)),
                ('note', models.TextField(blank=True)),
                ('actor_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_log', to='orders.order')),
            ],
            options={
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['order', 'timestamp'], name='orders_orde_order_i_497dbe_idx')],
            },
        ),
    ]
