# Generated by Django 6.0.4 on 2026-04-30 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_order_consignment_id_order_consignment_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='shipping_method',
            field=models.CharField(blank=True, choices=[('self-pickup', 'Hent i butikk (Ås)'), ('bring-pickup-point', 'Bring – hentested'), ('postnord-locker', 'PostNord pakkeboks')], db_index=True, max_length=24, null=True),
        ),
    ]
