# Generated by Django 6.0.5 on 2026-05-18 14:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("orders", "0006_alter_order_shipping_method"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="bundles_applied",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="order",
            name="coupon_code",
            field=models.CharField(
                blank=True, db_index=True, default="", max_length=40
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="coupon_free_shipping",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="order",
            name="discount_amount",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
