# Generated by Django 6.1.1 on 2026-09-05 21:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("orders", "0008_order_confirmation_emails_sent_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="status",
            field=models.CharField(
                choices=[
                    ("Mottatt", "Mottatt"),
                    ("Bekreftet", "Bekreftet"),
                    ("Pakkes", "Pakkes"),
                    ("Sendt", "Sendt"),
                    ("Levert", "Levert"),
                ],
                default="Mottatt",
                max_length=20,
            ),
        ),
    ]
