# Generated by Django 6.0.5 on 2026-05-18 14:32

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("products", "0003_truffle_is_active"),
    ]

    operations = [
        migrations.CreateModel(
            name="BundleRule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=120)),
                (
                    "description",
                    models.CharField(blank=True, default="", max_length=240),
                ),
                (
                    "variant_group",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Match products by their variant_group. Leave blank to use the explicit product list.",
                        max_length=64,
                    ),
                ),
                ("required_quantity", models.PositiveIntegerField(default=3)),
                ("bundle_price", models.DecimalField(decimal_places=2, max_digits=10)),
                ("includes_free_shipping", models.BooleanField(default=True)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("valid_from", models.DateTimeField(blank=True, null=True)),
                ("valid_to", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "products",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Explicit product list, used when variant_group is blank.",
                        related_name="bundle_rules",
                        to="products.product",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
