# Generated by Django 6.0.4 on 2026-04-26 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('number', models.CharField(max_length=5)),
                ('category', models.CharField(choices=[('Opprinnelse', 'Opprinnelse'), ('Håndverk', 'Håndverk'), ('Smaksnoter', 'Smaksnoter'), ('Folk', 'Folk')], max_length=50)),
                ('title', models.CharField(max_length=300)),
                ('blurb', models.TextField()),
                ('read_time', models.CharField(max_length=20)),
                ('published_at', models.CharField(max_length=50)),
                ('image', models.ImageField(blank=True, upload_to='articles/')),
                ('is_featured', models.BooleanField(default=False)),
                ('content', models.JSONField(default=list)),
            ],
            options={
                'ordering': ['-number'],
            },
        ),
        migrations.CreateModel(
            name='ContactSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('subject', models.CharField(max_length=300)),
                ('message', models.TextField()),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WaitlistEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('batch', models.CharField(default='05', max_length=10)),
                ('position', models.PositiveIntegerField(editable=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['position'],
                'unique_together': {('email', 'batch')},
            },
        ),
    ]
