# Generated by Django 6.1.1 on 2026-09-03 14:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("coupons", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="coupon",
            name="show_in_account",
            field=models.BooleanField(default=False),
        ),
    ]
