# Generated by Django 6.1.1 on 2026-09-23 10:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("horeca", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="company",
            name="invoice_country",
            field=models.CharField(blank=True, default="Norge", max_length=80),
        ),
    ]
