# Generated by Django 6.1.1 on 2026-09-23 10:49

import apps.horeca.models
import apps.horeca.storage
import datetime
import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("horeca", "0002_company_invoice_country"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="BlackoutDate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(unique=True)),
                ("reason", models.CharField(blank=True, default="", max_length=200)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["date"],
            },
        ),
        migrations.CreateModel(
            name="CapacityOverride",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(unique=True)),
                ("max_trays", models.PositiveIntegerField()),
                ("note", models.CharField(blank=True, default="", max_length=200)),
            ],
            options={
                "ordering": ["date"],
            },
        ),
        migrations.CreateModel(
            name="HorecaProduct",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("slug", models.SlugField(max_length=200, unique=True)),
                ("name", models.CharField(max_length=200)),
                (
                    "short_description",
                    models.CharField(blank=True, default="", max_length=300),
                ),
                ("description", models.TextField(blank=True, default="")),
                ("pieces_per_tray_plain", models.PositiveSmallIntegerField(default=88)),
                ("pieces_per_tray_logo", models.PositiveSmallIntegerField(default=81)),
                ("logo_available", models.BooleanField(default=True)),
                (
                    "wholesale_price",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                (
                    "vat_rate",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("15.00"), max_digits=5
                    ),
                ),
                ("ingredients_text", models.TextField(blank=True, default="")),
                ("allergens", models.JSONField(default=list)),
                ("traces_of", models.JSONField(default=list)),
                (
                    "net_weight_grams",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                (
                    "shelf_life_days",
                    models.PositiveSmallIntegerField(blank=True, null=True),
                ),
                (
                    "storage_text",
                    models.CharField(blank=True, default="", max_length=300),
                ),
                ("image", models.ImageField(blank=True, upload_to="horeca/products/")),
                (
                    "lead_time_days",
                    models.PositiveSmallIntegerField(blank=True, null=True),
                ),
                ("sort_order", models.PositiveSmallIntegerField(default=0)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["sort_order", "name"],
            },
        ),
        migrations.CreateModel(
            name="DeliveryAddress",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("label", models.CharField(max_length=120)),
                ("recipient", models.CharField(blank=True, default="", max_length=150)),
                (
                    "contact_name",
                    models.CharField(blank=True, default="", max_length=150),
                ),
                ("contact_phone", models.CharField(max_length=32)),
                ("street", models.CharField(max_length=300)),
                ("postal_code", models.CharField(max_length=10)),
                ("city", models.CharField(max_length=120)),
                ("country", models.CharField(default="Norge", max_length=80)),
                ("instructions", models.TextField(blank=True, default="")),
                ("is_default", models.BooleanField(default=False)),
                ("is_archived", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="addresses",
                        to="horeca.company",
                    ),
                ),
            ],
            options={
                "ordering": ["-is_default", "label"],
            },
        ),
        migrations.CreateModel(
            name="HorecaOrder",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "order_number",
                    models.CharField(editable=False, max_length=20, unique=True),
                ),
                (
                    "placed_by_name",
                    models.CharField(blank=True, default="", max_length=150),
                ),
                (
                    "placed_by_email",
                    models.EmailField(blank=True, default="", max_length=254),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("utkast", "Utkast"),
                            ("sendt", "Sendt"),
                            ("bekreftet", "Bekreftet"),
                            ("produksjon", "I produksjon"),
                            ("klar", "Klar til levering"),
                            ("levert", "Levert"),
                            ("avbestilt", "Avbestilt"),
                        ],
                        db_index=True,
                        default="utkast",
                        max_length=16,
                    ),
                ),
                ("is_draft", models.BooleanField(default=True)),
                (
                    "delivery_date",
                    models.DateField(blank=True, db_index=True, null=True),
                ),
                (
                    "delivery_window",
                    models.CharField(blank=True, default="", max_length=16),
                ),
                (
                    "delivery_window_label",
                    models.CharField(blank=True, default="", max_length=40),
                ),
                (
                    "company_name",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                ("org_number", models.CharField(blank=True, default="", max_length=32)),
                (
                    "delivery_label",
                    models.CharField(blank=True, default="", max_length=120),
                ),
                (
                    "delivery_recipient",
                    models.CharField(blank=True, default="", max_length=150),
                ),
                (
                    "delivery_contact_name",
                    models.CharField(blank=True, default="", max_length=150),
                ),
                (
                    "delivery_contact_phone",
                    models.CharField(blank=True, default="", max_length=32),
                ),
                (
                    "delivery_street",
                    models.CharField(blank=True, default="", max_length=300),
                ),
                (
                    "delivery_postal_code",
                    models.CharField(blank=True, default="", max_length=10),
                ),
                (
                    "delivery_city",
                    models.CharField(blank=True, default="", max_length=120),
                ),
                (
                    "delivery_country",
                    models.CharField(blank=True, default="Norge", max_length=80),
                ),
                ("delivery_instructions", models.TextField(blank=True, default="")),
                ("production_note", models.TextField(blank=True, default="")),
                ("internal_note", models.TextField(blank=True, default="")),
                (
                    "subtotal_ex_vat",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "vat_amount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "total_inc_vat",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                ("tray_count", models.PositiveIntegerField(default=0)),
                ("sent_at", models.DateTimeField(blank=True, null=True)),
                ("confirmed_at", models.DateTimeField(blank=True, null=True)),
                ("cancelled_at", models.DateTimeField(blank=True, null=True)),
                ("cancellation_reason", models.TextField(blank=True, default="")),
                (
                    "confirmation_emails_sent_at",
                    models.DateTimeField(blank=True, null=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "cancelled_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="orders",
                        to="horeca.company",
                    ),
                ),
                (
                    "delivery_address_source",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="horeca.deliveryaddress",
                    ),
                ),
                (
                    "placed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="horeca_orders",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="HorecaOrderEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "from_status",
                    models.CharField(blank=True, default="", max_length=16),
                ),
                ("to_status", models.CharField(blank=True, default="", max_length=16)),
                (
                    "actor_name",
                    models.CharField(blank=True, default="", max_length=150),
                ),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("portal", "Portal"),
                            ("admin", "Admin"),
                            ("system", "System"),
                        ],
                        default="system",
                        max_length=16,
                    ),
                ),
                ("note", models.TextField(blank=True, default="")),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    "actor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="events",
                        to="horeca.horecaorder",
                    ),
                ),
            ],
            options={
                "ordering": ["created_at"],
            },
        ),
        migrations.CreateModel(
            name="HorecaSettings",
            fields=[
                (
                    "singleton_id",
                    models.PositiveSmallIntegerField(
                        default=1, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("max_trays_per_day", models.PositiveIntegerField(default=40)),
                ("lead_time_days_plain", models.PositiveSmallIntegerField(default=3)),
                ("lead_time_days_logo", models.PositiveSmallIntegerField(default=7)),
                ("lead_time_in_working_days", models.BooleanField(default=True)),
                ("cutoff_time", models.TimeField(default=datetime.time(12, 0))),
                ("order_horizon_days", models.PositiveSmallIntegerField(default=180)),
                (
                    "delivery_weekdays",
                    models.JSONField(
                        default=apps.horeca.models._default_delivery_weekdays
                    ),
                ),
                (
                    "delivery_windows",
                    models.JSONField(
                        default=apps.horeca.models._default_delivery_windows
                    ),
                ),
                ("pieces_per_tray_plain", models.PositiveSmallIntegerField(default=88)),
                ("pieces_per_tray_logo", models.PositiveSmallIntegerField(default=81)),
                ("min_trays_per_order", models.PositiveSmallIntegerField(default=1)),
                ("max_trays_per_order", models.PositiveIntegerField(default=500)),
                ("cancel_deadline_days", models.PositiveSmallIntegerField(default=2)),
                (
                    "vat_rate",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("15.00"), max_digits=5
                    ),
                ),
                ("ordering_paused", models.BooleanField(default=False)),
                ("paused_message", models.TextField(blank=True, default="")),
                (
                    "contact_phone",
                    models.CharField(blank=True, default="", max_length=32),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "horeca settings",
            },
        ),
        migrations.CreateModel(
            name="Logo",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=120)),
                (
                    "file",
                    models.FileField(
                        max_length=255,
                        storage=apps.horeca.storage.private_logo_storage,
                        upload_to=apps.horeca.storage.logo_upload_to,
                    ),
                ),
                ("original_filename", models.CharField(max_length=255)),
                ("detected_format", models.CharField(max_length=8)),
                (
                    "kind",
                    models.CharField(
                        choices=[("raster", "Bilde"), ("vector", "Vektor")],
                        max_length=8,
                    ),
                ),
                (
                    "content_type",
                    models.CharField(blank=True, default="", max_length=100),
                ),
                ("byte_size", models.PositiveIntegerField()),
                ("checksum_sha256", models.CharField(db_index=True, max_length=64)),
                ("width_px", models.PositiveIntegerField(blank=True, null=True)),
                ("height_px", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Til godkjenning"),
                            ("approved", "Godkjent"),
                            ("rejected", "Avvist"),
                        ],
                        db_index=True,
                        default="pending",
                        max_length=16,
                    ),
                ),
                ("rejection_reason", models.TextField(blank=True, default="")),
                ("reviewed_at", models.DateTimeField(blank=True, null=True)),
                ("is_archived", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="logos",
                        to="horeca.company",
                    ),
                ),
                (
                    "reviewed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "uploaded_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="HorecaOrderLine",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("product_name", models.CharField(max_length=200)),
                (
                    "product_slug",
                    models.CharField(blank=True, default="", max_length=200),
                ),
                ("tray_count", models.PositiveIntegerField()),
                ("with_logo", models.BooleanField(default=False)),
                ("logo_name", models.CharField(blank=True, default="", max_length=120)),
                ("pieces_per_tray", models.PositiveSmallIntegerField()),
                ("piece_count", models.PositiveIntegerField()),
                (
                    "unit_price_ex_vat",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                ("price_source", models.CharField(default="list", max_length=24)),
                (
                    "vat_rate",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("15.00"), max_digits=5
                    ),
                ),
                (
                    "line_total_ex_vat",
                    models.DecimalField(decimal_places=2, max_digits=12),
                ),
                ("allergens_snapshot", models.JSONField(default=list)),
                ("ingredients_snapshot", models.TextField(blank=True, default="")),
                ("line_note", models.CharField(blank=True, default="", max_length=300)),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lines",
                        to="horeca.horecaorder",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="horeca.horecaproduct",
                    ),
                ),
                (
                    "logo",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="order_lines",
                        to="horeca.logo",
                    ),
                ),
            ],
            options={
                "ordering": ["id"],
            },
        ),
        migrations.AddConstraint(
            model_name="deliveryaddress",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_archived", False), ("is_default", True)),
                fields=("company",),
                name="one_default_address_per_company",
            ),
        ),
        migrations.AddIndex(
            model_name="horecaorder",
            index=models.Index(
                fields=["delivery_date", "status"],
                name="horeca_hore_deliver_e01028_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="horecaorder",
            index=models.Index(
                fields=["company", "-created_at"], name="horeca_hore_company_e653fc_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="horecaorder",
            index=models.Index(
                fields=["status", "delivery_date"], name="horeca_hore_status_cca2bf_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="horecaorderevent",
            index=models.Index(
                fields=["order", "created_at"], name="horeca_hore_order_i_fad4b6_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="logo",
            index=models.Index(
                fields=["company", "status"], name="horeca_logo_company_3cc774_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="horecaorderline",
            constraint=models.CheckConstraint(
                condition=models.Q(("tray_count__gte", 1)),
                name="horeca_line_min_one_tray",
            ),
        ),
        migrations.AddConstraint(
            model_name="horecaorderline",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("logo__isnull", True), ("with_logo", False)),
                    models.Q(("logo__isnull", False), ("with_logo", True)),
                    _connector="OR",
                ),
                name="horeca_line_logo_consistency",
            ),
        ),
    ]
