# Generated by Django 6.1.1 on 2026-09-23 10:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("horeca", "0005_seed_horeca_settings"),
    ]

    operations = [
        migrations.AlterField(
            model_name="horecaorder",
            name="order_number",
            field=models.CharField(
                blank=True, editable=False, max_length=20, null=True, unique=True
            ),
        ),
    ]
