# Generated by Django 6.0.4 on 2026-04-29 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_customuser_address_customuser_city_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='user_type',
            field=models.CharField(choices=[('registered', 'Registered'), ('guest', 'Guest')], db_index=True, default='registered', max_length=12),
        ),
    ]
