# Generated by Django 6.1.1 on 2026-09-23 10:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0006_customuser_is_seen"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="user_type",
            field=models.CharField(
                choices=[
                    ("registered", "Registered"),
                    ("guest", "Guest"),
                    ("horeca", "HORECA"),
                ],
                db_index=True,
                default="registered",
                max_length=12,
            ),
        ),
    ]
